"""initial

Revision ID: 0713cc4e308e
Revises: 
Create Date: 2026-05-01 14:37:02.525168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0713cc4e308e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('status', sa.Enum('done', 'provision', name='transactionstatus'), nullable=False))
    op.add_column('transactions', sa.Column('payment_method', sa.Enum('credit_card', 'account', name='paymentmethod'), nullable=True))
    op.add_column('transactions', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_recurring')
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'status')
    # ### end Alembic commands ###
