"""add_balance_snapshot_to_users

Revision ID: eb0e1b351f2a
Revises: 981f2f39cfc0
Create Date: 2026-05-05 15:09:34.520770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0e1b351f2a'
down_revision: Union[str, Sequence[str], None] = '981f2f39cfc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance_snapshot_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('users', sa.Column('balance_snapshot_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance_snapshot_date')
    op.drop_column('users', 'balance_snapshot_amount')
    # ### end Alembic commands ###
