"""categories_per_user

Revision ID: f0dccd00a07c
Revises: a00bbadd2a7f
Create Date: 2026-05-01 18:42:40.072779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0dccd00a07c'
down_revision: Union[str, Sequence[str], None] = 'a00bbadd2a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('transaction_categories_name_key'), 'transaction_categories', type_='unique')
    op.create_unique_constraint('uq_category_name_user', 'transaction_categories', ['name', 'user_id'])
    op.create_foreign_key(None, 'transaction_categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_categories', type_='foreignkey')
    op.drop_constraint('uq_category_name_user', 'transaction_categories', type_='unique')
    op.create_unique_constraint(op.f('transaction_categories_name_key'), 'transaction_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('transaction_categories', 'user_id')
    # ### end Alembic commands ###
